# This is a basic workflow to help you get started with Actions

name: Build and Push Image

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build and push image
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v2

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ubi7
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./UBI7/Dockerfile

    - name: Push To Registry
      uses: redhat-actions/push-to-registry@v2.6
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Print image url
      run: echo "Image pushed to registry."
